/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.ed.hashmusic.viewmodel;

import br.ufjf.ed.hashmusic.model.MusicInfo;
import br.ufjf.ed.hashmusic.repository.Mp3Repository;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author -Igor
 */
public class CollisionWindow extends javax.swing.JFrame {

    /**
     * Creates new form CollisionWindow
     */
    // Repositório de músicas Mp3
    private final Mp3Repository repository;

    public CollisionWindow() throws IOException 
    {
        initComponents();
        setLocationRelativeTo(null);
        
        this.repository = new Mp3Repository();
        this.repository.loadRepository();
        
        calculateCollisions();
    }

    private void calculateCollisions() {
        List<MusicInfo> musics = repository.getRepositoryList();
        
        if (musics.size() > 0) {
            ArrayList<String> existentName = new ArrayList<>();
            ArrayList<String> existentDir = new ArrayList<>();
            
            ArrayList<String> colidedName = new ArrayList<>();
            ArrayList<String> colidedDir = new ArrayList<>();
            
            int colideName = 0;
            int colideDir = 0;

            for (MusicInfo m : musics) {
                String hashName = repository.getHashName(m);
                String hashDir = repository.getHashDir(m);
                
                if (existentName.contains(hashName)) {
                    if (!colidedName.contains(hashName)) {
                        colidedName.add(hashName);
                    }

                    colideName++;
                } else {
                    existentName.add(hashName);
                }

                if (existentDir.contains(hashDir)) {
                    if (!colidedDir.contains(hashDir)) {
                        colidedDir.add(hashDir);
                    }

                    colideDir++;
                } else {
                    existentDir.add(hashDir);
                }

            }

            totalName.setText(String.valueOf((float)colideName / musics.size()));
            mediumName.setText(String.valueOf((float)colideName / colidedName.size()));
            totalColidedName.setText(String.valueOf(colideName));
            totalDir.setText(String.valueOf((float)colideDir / musics.size()));
            mediumDir.setText(String.valueOf((float)colideDir / colidedDir.size()));
            totalColidedDir.setText(String.valueOf(colideDir));
            
        } else {
            
            totalName.setText(String.valueOf(0));
            mediumName.setText(String.valueOf(0));
            totalColidedName.setText(String.valueOf(0));
            totalDir.setText(String.valueOf(0));
            mediumDir.setText(String.valueOf(0));
            totalColidedDir.setText(String.valueOf(0));
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTotalName = new javax.swing.JLabel();
        totalName = new javax.swing.JLabel();
        labelMediumName = new javax.swing.JLabel();
        mediumName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelTotalDir = new javax.swing.JLabel();
        labelMediumDir = new javax.swing.JLabel();
        totalDir = new javax.swing.JLabel();
        mediumDir = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        labelTotalColidedName = new javax.swing.JLabel();
        labelTotalColidedDir = new javax.swing.JLabel();
        totalColidedDir = new javax.swing.JLabel();
        totalColidedName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitButton.setText("Sair");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Relatório de Colisões");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Hashing de Nome");

        labelTotalName.setText("Quantidade Média de Colisões Totais ");

        totalName.setText("totalName");

        labelMediumName.setText("Distribuição Média das Colisões");

        mediumName.setText("mediumName");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Hashing de Diretório");

        labelTotalDir.setText("Quantdade Média de Colisões Totais ");

        labelMediumDir.setText("Distribuição Média das Colisões");

        totalDir.setText("totalDir");

        mediumDir.setText("mediumDir");

        updateButton.setText("Atualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        labelTotalColidedName.setText("Total de Colisões");

        labelTotalColidedDir.setText("Total de Colisões");

        totalColidedDir.setText("totalColidedDir");

        totalColidedName.setText("totalColidedName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMediumDir)
                                .addGap(47, 47, 47)
                                .addComponent(mediumDir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotalDir)
                                    .addComponent(labelTotalColidedDir))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalColidedDir)
                                    .addComponent(totalDir)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotalName)
                                    .addComponent(labelMediumName)
                                    .addComponent(labelTotalColidedName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalColidedName)
                                    .addComponent(mediumName)
                                    .addComponent(totalName))))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalColidedName)
                    .addComponent(totalColidedName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalName)
                    .addComponent(totalName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMediumName)
                    .addComponent(mediumName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalColidedDir)
                    .addComponent(totalColidedDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalDir)
                    .addComponent(totalDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMediumDir)
                    .addComponent(mediumDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(updateButton))
                .addContainerGap())
        );

        labelTotalName.getAccessibleContext().setAccessibleName("jLabel3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        calculateCollisions();
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollisionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollisionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollisionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollisionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CollisionWindow().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CollisionWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelMediumDir;
    private javax.swing.JLabel labelMediumName;
    private javax.swing.JLabel labelTotalColidedDir;
    private javax.swing.JLabel labelTotalColidedName;
    private javax.swing.JLabel labelTotalDir;
    private javax.swing.JLabel labelTotalName;
    private javax.swing.JLabel mediumDir;
    private javax.swing.JLabel mediumName;
    private javax.swing.JLabel totalColidedDir;
    private javax.swing.JLabel totalColidedName;
    private javax.swing.JLabel totalDir;
    private javax.swing.JLabel totalName;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
